# Список путей к потенциально «забытым»/резервным файлам,
# которые могут содержать важную информацию.
paths:
  - .env
  - backup.sql
  - db_backup.sql
  - config.bak
  - config.old
  - wp-config.php.bak
  - .git/config
  - .gitignore
  - composer.lock
  - composer.json.bak
  - package-lock.json
  - README.md
  - logs/error.log
  - logs/debug.log
  - .htaccess
  - .htpasswd
  - adminer.php
  - phpinfo.php
  - config/config.php.bak

# timeoutSeconds - время ожидания ответа от сервера (в секундах)
timeoutSeconds: 10

# validStatusCodes - список кодов, которые считаем "доступностью" файла
# (по умолчанию 200, 302). Вы можете сами решить, какие коды считать интересными.
validStatusCodes:
  - 200
  - 302
  - 301
  # Примерно 403 иногда указывает, что файл существует, но доступ к нему закрыт
  # - 403

# verbose - если true, сканер будет выводить дополнительную отладочную информацию
verbose: true
